#ifdef PCIE20
#define PCIE_BASE_reg_addr                                                         0xD803B000
#define PCIE_SYS_CTR                                                               0x9803BC00
#define PCIE_SYS_CTR_reg_addr                                                      "0xD803BC00"
#define PCIE_SYS_CTR_reg                                                           0xD803BC00
#define PCIE_INT_CTR                                                               0x9803BC04
#define PCIE_INT_CTR_reg_addr                                                      "0xD803BC04"
#define PCIE_INT_CTR_reg                                                           0xD803BC04
#define PCIE_GNR_INT                                                               0x9803BC08
#define PCIE_GNR_INT_reg_addr                                                      "0xD803BC08"
#define PCIE_GNR_INT_reg                                                           0xD803BC08
#define PCIE_PCIE_INT                                                              0x9803BC0C
#define PCIE_PCIE_INT_reg_addr                                                     "0xD803BC0C"
#define PCIE_PCIE_INT_reg                                                          0xD803BC0C
#define PCIE_DBI_CTR                                                               0x9803BC10
#define PCIE_DBI_CTR_reg_addr                                                      "0xD803BC10"
#define PCIE_DBI_CTR_reg                                                           0xD803BC10
#define PCIE_INDIR_CTR                                                             0x9803BC14
#define PCIE_INDIR_CTR_reg_addr                                                    "0xD803BC14"
#define PCIE_INDIR_CTR_reg                                                         0xD803BC14
#define PCIE_DIR_CTR                                                               0x9803BC18
#define PCIE_DIR_CTR_reg_addr                                                      "0xD803BC18"
#define PCIE_DIR_CTR_reg                                                           0xD803BC18
#define PCIE_MDIO_CTR                                                              0x9803BC1C
#define PCIE_MDIO_CTR_reg_addr                                                     "0xD803BC1C"
#define PCIE_MDIO_CTR_reg                                                          0xD803BC1C
#define PCIE_PCIE_BASE0                                                            0x9803BC20
#define PCIE_PCIE_BASE0_reg_addr                                                   "0xD803BC20"
#define PCIE_PCIE_BASE0_reg                                                        0xD803BC20
#define PCIE_PCIE_BASE1                                                            0x9803BC24
#define PCIE_PCIE_BASE1_reg_addr                                                   "0xD803BC24"
#define PCIE_PCIE_BASE1_reg                                                        0xD803BC24
#define PCIE_PCIE_MASK0                                                            0x9803BC28
#define PCIE_PCIE_MASK0_reg_addr                                                   "0xD803BC28"
#define PCIE_PCIE_MASK0_reg                                                        0xD803BC28
#define PCIE_PCIE_MASK1                                                            0x9803BC2C
#define PCIE_PCIE_MASK1_reg_addr                                                   "0xD803BC2C"
#define PCIE_PCIE_MASK1_reg                                                        0xD803BC2C
#define PCIE_PCIE_TRAN0                                                            0x9803BC30
#define PCIE_PCIE_TRAN0_reg_addr                                                   "0xD803BC30"
#define PCIE_PCIE_TRAN0_reg                                                        0xD803BC30
#define PCIE_PCIE_TRAN1                                                            0x9803BC34
#define PCIE_PCIE_TRAN1_reg_addr                                                   "0xD803BC34"
#define PCIE_PCIE_TRAN1_reg                                                        0xD803BC34
#define PCIE_CFG_CT                                                                0x9803BC38
#define PCIE_CFG_CT_reg_addr                                                       "0xD803BC38"
#define PCIE_CFG_CT_reg                                                            0xD803BC38
#define PCIE_CFG_EN                                                                0x9803BC3C
#define PCIE_CFG_EN_reg_addr                                                       "0xD803BC3C"
#define PCIE_CFG_EN_reg                                                            0xD803BC3C
#define PCIE_CFG_ST                                                                0x9803BC40
#define PCIE_CFG_ST_reg_addr                                                       "0xD803BC40"
#define PCIE_CFG_ST_reg                                                            0xD803BC40
#define PCIE_CFG_ADDR                                                              0x9803BC44
#define PCIE_CFG_ADDR_reg_addr                                                     "0xD803BC44"
#define PCIE_CFG_ADDR_reg                                                          0xD803BC44
#define PCIE_CFG_WDATA                                                             0x9803BC48
#define PCIE_CFG_WDATA_reg_addr                                                    "0xD803BC48"
#define PCIE_CFG_WDATA_reg                                                         0xD803BC48
#define PCIE_CFG_RDATA                                                             0x9803BC4C
#define PCIE_CFG_RDATA_reg_addr                                                    "0xD803BC4C"
#define PCIE_CFG_RDATA_reg                                                         0xD803BC4C
#define PCIE_MIO_CT                                                                0x9803BC50
#define PCIE_MIO_CT_reg_addr                                                       "0xD803BC50"
#define PCIE_MIO_CT_reg                                                            0xD803BC50
#define PCIE_MIO_ST                                                                0x9803BC54
#define PCIE_MIO_ST_reg_addr                                                       "0xD803BC54"
#define PCIE_MIO_ST_reg                                                            0xD803BC54
#define PCIE_MIO_EN                                                                0x9803BC58
#define PCIE_MIO_EN_reg_addr                                                       "0xD803BC58"
#define PCIE_MIO_EN_reg                                                            0xD803BC58
#define PCIE_MIO_ADDR                                                              0x9803BC5C
#define PCIE_MIO_ADDR_reg_addr                                                     "0xD803BC5C"
#define PCIE_MIO_ADDR_reg                                                          0xD803BC5C
#define PCIE_MIO_WDATA                                                             0x9803BC60
#define PCIE_MIO_WDATA_reg_addr                                                    "0xD803BC60"
#define PCIE_MIO_WDATA_reg                                                         0xD803BC60
#define PCIE_MIO_RDATA                                                             0x9803BC64
#define PCIE_MIO_RDATA_reg_addr                                                    "0xD803BC64"
#define PCIE_MIO_RDATA_reg                                                         0xD803BC64
#define PCIE_PHY_CTR                                                               0x9803BC68
#define PCIE_PHY_CTR_reg_addr                                                      "0xD803BC68"
#define PCIE_PHY_CTR_reg                                                           0xD803BC68
#define PCIE_PWR_CTR                                                               0x9803BC6C
#define PCIE_PWR_CTR_reg_addr                                                      "0xD803BC6C"
#define PCIE_PWR_CTR_reg                                                           0xD803BC6C
#define PCIE_PCIE_DBG                                                              0x9803BC70
#define PCIE_PCIE_DBG_reg_addr                                                     "0xD803BC70"
#define PCIE_PCIE_DBG_reg                                                          0xD803BC70
#define PCIE_DIR_ST                                                                0x9803BC74
#define PCIE_DIR_ST_reg_addr                                                       "0xD803BC74"
#define PCIE_DIR_ST_reg                                                            0xD803BC74
#define PCIE_DIR_EN                                                                0x9803BC78
#define PCIE_DIR_EN_reg_addr                                                       "0xD803BC78"
#define PCIE_DIR_EN_reg                                                            0xD803BC78
#define PCIE_RCPL_ST                                                               0x9803BC7C
#define PCIE_RCPL_ST_reg_addr                                                      "0xD803BC7C"
#define PCIE_RCPL_ST_reg                                                           0xD803BC7C
#define PCIE_RCPL_ADR                                                              0x9803BC80
#define PCIE_RCPL_ADR_reg_addr                                                     "0xD803BC80"
#define PCIE_RCPL_ADR_reg                                                          0xD803BC80
#define PCIE_RCPL_TOUT0                                                            0x9803BC84
#define PCIE_RCPL_TOUT0_reg_addr                                                   "0xD803BC84"
#define PCIE_RCPL_TOUT0_reg                                                        0xD803BC84
#define PCIE_RCPL_TOUT1                                                            0x9803BC88
#define PCIE_RCPL_TOUT1_reg_addr                                                   "0xD803BC88"
#define PCIE_RCPL_TOUT1_reg                                                        0xD803BC88
#define PCIE_RTGT_ST                                                               0x9803BC8C
#define PCIE_RTGT_ST_reg_addr                                                      "0xD803BC8C"
#define PCIE_RTGT_ST_reg                                                           0xD803BC8C
#define PCIE_RTGT_ADR                                                              0x9803BC90
#define PCIE_RTGT_ADR_reg_addr                                                     "0xD803BC90"
#define PCIE_RTGT_ADR_reg                                                          0xD803BC90
#define PCIE_RTGT_TOUT0                                                            0x9803BC94
#define PCIE_RTGT_TOUT0_reg_addr                                                   "0xD803BC94"
#define PCIE_RTGT_TOUT0_reg                                                        0xD803BC94
#define PCIE_RTGT_TOUT1                                                            0x9803BC98
#define PCIE_RTGT_TOUT1_reg_addr                                                   "0xD803BC98"
#define PCIE_RTGT_TOUT1_reg                                                        0xD803BC98
#define PCIE_AERRO_ST                                                              0x9803BC9C
#define PCIE_AERRO_ST_reg_addr                                                     "0xD803BC9C"
#define PCIE_AERRO_ST_reg                                                          0xD803BC9C
#define PCIE_AEMSI_ST                                                              0x9803BCA0
#define PCIE_AEMSI_ST_reg_addr                                                     "0xD803BCA0"
#define PCIE_AEMSI_ST_reg                                                          0xD803BCA0
#define PCIE_PME_ST                                                                0x9803BCA4
#define PCIE_PME_ST_reg_addr                                                       "0xD803BCA4"
#define PCIE_PME_ST_reg                                                            0xD803BCA4
#define PCIE_PMMSI_ST                                                              0x9803BCA8
#define PCIE_PMMSI_ST_reg_addr                                                     "0xD803BCA8"
#define PCIE_PMMSI_ST_reg                                                          0xD803BCA8
#define PCIE_VEN_MSG0                                                              0x9803BCAC
#define PCIE_VEN_MSG0_reg_addr                                                     "0xD803BCAC"
#define PCIE_VEN_MSG0_reg                                                          0xD803BCAC
#define PCIE_VEN_MSG1                                                              0x9803BCB0
#define PCIE_VEN_MSG1_reg_addr                                                     "0xD803BCB0"
#define PCIE_VEN_MSG1_reg                                                          0xD803BCB0
#define PCIE_MAC_ST                                                                0x9803BCB4
#define PCIE_MAC_ST_reg_addr                                                       "0xD803BCB4"
#define PCIE_MAC_ST_reg                                                            0xD803BCB4
#define PCIE_UNLOCK_MSG                                                            0x9803BCB8
#define PCIE_UNLOCK_MSG_reg_addr                                                   "0xD803BCB8"
#define PCIE_UNLOCK_MSG_reg                                                        0xD803BCB8
#define PCIE_SCTCH                                                                 0x9803BCBC
#define PCIE_SCTCH_reg_addr                                                        "0xD803BCBC"
#define PCIE_SCTCH_reg                                                             0xD803BCBC
#define PCIE_LOOP_DATA_2_reg_addr                                                  "0xD803BCC8"
#define PCIE_LOOP_DATA_3_reg_addr                                                  "0xD803BCCC"
#define PCIE_LOOP_DATA_0_reg                                                       0xD803BCC0
#define PCIE_MSI_TRAN                                                              0x9803BCD0
#define PCIE_MSI_TRAN_reg_addr                                                     "0xD803BCD0"
#define PCIE_MSI_TRAN_reg                                                          0xD803BCD0
#define PCIE_MSI_DATA                                                              0x9803BCD4
#define PCIE_MSI_DATA_reg_addr                                                     "0xD803BCD4"
#define PCIE_MSI_DATA_reg                                                          0xD803BCD4
#define PCIE_LINK_ST                                                               0x9803BCE8
#define PCIE_LINK_ST_reg_addr                                                      "0xD803BCE8"
#define PCIE_LINK_ST_reg                                                           0xD803BCE8
#define PCIE_BIST_CTRL                                                             0x9803BCEC
#define PCIE_BIST_CTRL_reg_addr                                                    "0xD803BCEC"
#define PCIE_BIST_CTRL_reg                                                         0xD803BCEC
#define PCIE_BIST_STATUS                                                           0x9803BCF0
#define PCIE_BIST_STATUS_reg_addr                                                  "0xD803BCF0"
#define PCIE_BIST_STATUS_reg                                                       0xD803BCF0
#define PCIE_SRAM_PWRDN                                                            0x9803BCF4
#define PCIE_SRAM_PWRDN_reg_addr                                                   "0xD803BCF4"
#define PCIE_SRAM_PWRDN_reg                                                        0xD803BCF4
#define PCIE_VEN_MSG2                                                              0x9803BCF8
#define PCIE_VEN_MSG2_reg_addr                                                     "0xD803BCF8"
#define PCIE_VEN_MSG2_reg                                                          0xD803BCF8
#define PCIE_PCI_BASE                                                              0x9803BCFC
#define PCIE_PCI_BASE_reg_addr                                                     "0xD803BCFC"
#define PCIE_PCI_BASE_reg                                                          0xD803BCFC
#define PCIE_PCI_MASK                                                              0x9803BD00
#define PCIE_PCI_MASK_reg_addr                                                     "0xD803BD00"
#define PCIE_PCI_MASK_reg                                                          0xD803BD00
#define PCIE_PCI_TRANS                                                             0x9803BD04
#define PCIE_PCI_TRANS_reg_addr                                                    "0xD803BD04"
#define PCIE_PCI_TRANS_reg                                                         0xD803BD04
#define PCIE_PCI_LTR                                                               0x9803BD08
#define PCIE_PCI_LTR_reg_addr                                                      "0xD803BD08"
#define PCIE_PCI_LTR_reg                                                           0xD803BD08
#define PCIE_TMP_REG_3                                                             0x9803BCE4
#define PCIE_TMP_REG_0_reg_addr                                                    "0xD803BCD8"
#define PCIE_TMP_REG_1_reg_addr                                                    "0xD803BCDC"
#define PCIE_TMP_REG_2_reg_addr                                                    "0xD803BCE0"
#define PCIE_TMP_REG_3_reg_addr                                                    "0xD803BCE4"
#define PCIE_TMP_REG_0_reg                                                         0xD803BCD8
#define PCIE_TMP_REG_1_reg                                                         0xD803BCDC
#define PCIE_TMP_REG_2_reg                                                         0xD803BCE0
#define PCIE_TMP_REG_3_reg                                                         0xD803BCE4
#define PCIE_MAC_ID                                                                0x119720ec
#define PCIE_CLKREQ_MUX_PAD                                                        0x00000010
#define PCIE_0x7C_LINK_CAPABILITY                                                  0x00737c12
#define PCIE_0x80_LINK_CAPABILITY                                                  0x38110008
#define PCIE_0x9C_LINK_CAPABILITY2                                                 0x00000006
//#define PCIE_0xa0_LINK_CONTROL2_LINK_STATUS2                                       0x00010002
#define PCIE_0xa0_LINK_CONTROL2_LINK_STATUS2                                       0x00000002
#define PCIE_PCI_EP_BASE_PA                                                        0x9803C000
#define PCIE_PCI_EP_BASE_VA                                                        0xD803C000
#else
#define PCIE_BASE_reg_addr                                                         0xD804E000
#define PCIE_SYS_CTR                                                               0x9804EC00
#define PCIE_SYS_CTR_reg_addr                                                      "0xD804EC00"
#define PCIE_SYS_CTR_reg                                                           0xD804EC00
#define PCIE_INT_CTR                                                               0x9804EC04
#define PCIE_INT_CTR_reg_addr                                                      "0xD804EC04"
#define PCIE_INT_CTR_reg                                                           0xD804EC04
#define PCIE_GNR_INT                                                               0x9804EC08
#define PCIE_GNR_INT_reg_addr                                                      "0xD804EC08"
#define PCIE_GNR_INT_reg                                                           0xD804EC08
#define PCIE_PCIE_INT                                                              0x9804EC0C
#define PCIE_PCIE_INT_reg_addr                                                     "0xD804EC0C"
#define PCIE_PCIE_INT_reg                                                          0xD804EC0C
#define PCIE_DBI_CTR                                                               0x9804EC10
#define PCIE_DBI_CTR_reg_addr                                                      "0xD804EC10"
#define PCIE_DBI_CTR_reg                                                           0xD804EC10
#define PCIE_INDIR_CTR                                                             0x9804EC14
#define PCIE_INDIR_CTR_reg_addr                                                    "0xD804EC14"
#define PCIE_INDIR_CTR_reg                                                         0xD804EC14
#define PCIE_DIR_CTR                                                               0x9804EC18
#define PCIE_DIR_CTR_reg_addr                                                      "0xD804EC18"
#define PCIE_DIR_CTR_reg                                                           0xD804EC18
#define PCIE_MDIO_CTR                                                              0x9804EC1C
#define PCIE_MDIO_CTR_reg_addr                                                     "0xD804EC1C"
#define PCIE_MDIO_CTR_reg                                                          0xD804EC1C
#define PCIE_PCIE_BASE0                                                            0x9804EC20
#define PCIE_PCIE_BASE0_reg_addr                                                   "0xD804EC20"
#define PCIE_PCIE_BASE0_reg                                                        0xD804EC20
#define PCIE_PCIE_BASE1                                                            0x9804EC24
#define PCIE_PCIE_BASE1_reg_addr                                                   "0xD804EC24"
#define PCIE_PCIE_BASE1_reg                                                        0xD804EC24
#define PCIE_PCIE_MASK0                                                            0x9804EC28
#define PCIE_PCIE_MASK0_reg_addr                                                   "0xD804EC28"
#define PCIE_PCIE_MASK0_reg                                                        0xD804EC28
#define PCIE_PCIE_MASK1                                                            0x9804EC2C
#define PCIE_PCIE_MASK1_reg_addr                                                   "0xD804EC2C"
#define PCIE_PCIE_MASK1_reg                                                        0xD804EC2C
#define PCIE_PCIE_TRAN0                                                            0x9804EC30
#define PCIE_PCIE_TRAN0_reg_addr                                                   "0xD804EC30"
#define PCIE_PCIE_TRAN0_reg                                                        0xD804EC30
#define PCIE_PCIE_TRAN1                                                            0x9804EC34
#define PCIE_PCIE_TRAN1_reg_addr                                                   "0xD804EC34"
#define PCIE_PCIE_TRAN1_reg                                                        0xD804EC34
#define PCIE_CFG_CT                                                                0x9804EC38
#define PCIE_CFG_CT_reg_addr                                                       "0xD804EC38"
#define PCIE_CFG_CT_reg                                                            0xD804EC38
#define PCIE_CFG_EN                                                                0x9804EC3C
#define PCIE_CFG_EN_reg_addr                                                       "0xD804EC3C"
#define PCIE_CFG_EN_reg                                                            0xD804EC3C
#define PCIE_CFG_ST                                                                0x9804EC40
#define PCIE_CFG_ST_reg_addr                                                       "0xD804EC40"
#define PCIE_CFG_ST_reg                                                            0xD804EC40
#define PCIE_CFG_ADDR                                                              0x9804EC44
#define PCIE_CFG_ADDR_reg_addr                                                     "0xD804EC44"
#define PCIE_CFG_ADDR_reg                                                          0xD804EC44
#define PCIE_CFG_WDATA                                                             0x9804EC48
#define PCIE_CFG_WDATA_reg_addr                                                    "0xD804EC48"
#define PCIE_CFG_WDATA_reg                                                         0xD804EC48
#define PCIE_CFG_RDATA                                                             0x9804EC4C
#define PCIE_CFG_RDATA_reg_addr                                                    "0xD804EC4C"
#define PCIE_CFG_RDATA_reg                                                         0xD804EC4C
#define PCIE_MIO_CT                                                                0x9804EC50
#define PCIE_MIO_CT_reg_addr                                                       "0xD804EC50"
#define PCIE_MIO_CT_reg                                                            0xD804EC50
#define PCIE_MIO_ST                                                                0x9804EC54
#define PCIE_MIO_ST_reg_addr                                                       "0xD804EC54"
#define PCIE_MIO_ST_reg                                                            0xD804EC54
#define PCIE_MIO_EN                                                                0x9804EC58
#define PCIE_MIO_EN_reg_addr                                                       "0xD804EC58"
#define PCIE_MIO_EN_reg                                                            0xD804EC58
#define PCIE_MIO_ADDR                                                              0x9804EC5C
#define PCIE_MIO_ADDR_reg_addr                                                     "0xD804EC5C"
#define PCIE_MIO_ADDR_reg                                                          0xD804EC5C
#define PCIE_MIO_WDATA                                                             0x9804EC60
#define PCIE_MIO_WDATA_reg_addr                                                    "0xD804EC60"
#define PCIE_MIO_WDATA_reg                                                         0xD804EC60
#define PCIE_MIO_RDATA                                                             0x9804EC64
#define PCIE_MIO_RDATA_reg_addr                                                    "0xD804EC64"
#define PCIE_MIO_RDATA_reg                                                         0xD804EC64
#define PCIE_PHY_CTR                                                               0x9804EC68
#define PCIE_PHY_CTR_reg_addr                                                      "0xD804EC68"
#define PCIE_PHY_CTR_reg                                                           0xD804EC68
#define PCIE_PWR_CTR                                                               0x9804EC6C
#define PCIE_PWR_CTR_reg_addr                                                      "0xD804EC6C"
#define PCIE_PWR_CTR_reg                                                           0xD804EC6C
#define PCIE_PCIE_DBG                                                              0x9804EC70
#define PCIE_PCIE_DBG_reg_addr                                                     "0xD804EC70"
#define PCIE_PCIE_DBG_reg                                                          0xD804EC70
#define PCIE_DIR_ST                                                                0x9804EC74
#define PCIE_DIR_ST_reg_addr                                                       "0xD804EC74"
#define PCIE_DIR_ST_reg                                                            0xD804EC74
#define PCIE_DIR_EN                                                                0x9804EC78
#define PCIE_DIR_EN_reg_addr                                                       "0xD804EC78"
#define PCIE_DIR_EN_reg                                                            0xD804EC78
#define PCIE_RCPL_ST                                                               0x9804EC7C
#define PCIE_RCPL_ST_reg_addr                                                      "0xD804EC7C"
#define PCIE_RCPL_ST_reg                                                           0xD804EC7C
#define PCIE_RCPL_ADR                                                              0x9804EC80
#define PCIE_RCPL_ADR_reg_addr                                                     "0xD804EC80"
#define PCIE_RCPL_ADR_reg                                                          0xD804EC80
#define PCIE_RCPL_TOUT0                                                            0x9804EC84
#define PCIE_RCPL_TOUT0_reg_addr                                                   "0xD804EC84"
#define PCIE_RCPL_TOUT0_reg                                                        0xD804EC84
#define PCIE_RCPL_TOUT1                                                            0x9804EC88
#define PCIE_RCPL_TOUT1_reg_addr                                                   "0xD804EC88"
#define PCIE_RCPL_TOUT1_reg                                                        0xD804EC88
#define PCIE_RTGT_ST                                                               0x9804EC8C
#define PCIE_RTGT_ST_reg_addr                                                      "0xD804EC8C"
#define PCIE_RTGT_ST_reg                                                           0xD804EC8C
#define PCIE_RTGT_ADR                                                              0x9804EC90
#define PCIE_RTGT_ADR_reg_addr                                                     "0xD804EC90"
#define PCIE_RTGT_ADR_reg                                                          0xD804EC90
#define PCIE_RTGT_TOUT0                                                            0x9804EC94
#define PCIE_RTGT_TOUT0_reg_addr                                                   "0xD804EC94"
#define PCIE_RTGT_TOUT0_reg                                                        0xD804EC94
#define PCIE_RTGT_TOUT1                                                            0x9804EC98
#define PCIE_RTGT_TOUT1_reg_addr                                                   "0xD804EC98"
#define PCIE_RTGT_TOUT1_reg                                                        0xD804EC98
#define PCIE_AERRO_ST                                                              0x9804EC9C
#define PCIE_AERRO_ST_reg_addr                                                     "0xD804EC9C"
#define PCIE_AERRO_ST_reg                                                          0xD804EC9C
#define PCIE_AEMSI_ST                                                              0x9804ECA0
#define PCIE_AEMSI_ST_reg_addr                                                     "0xD804ECA0"
#define PCIE_AEMSI_ST_reg                                                          0xD804ECA0
#define PCIE_PME_ST                                                                0x9804ECA4
#define PCIE_PME_ST_reg_addr                                                       "0xD804ECA4"
#define PCIE_PME_ST_reg                                                            0xD804ECA4
#define PCIE_PMMSI_ST                                                              0x9804ECA8
#define PCIE_PMMSI_ST_reg_addr                                                     "0xD804ECA8"
#define PCIE_PMMSI_ST_reg                                                          0xD804ECA8
#define PCIE_VEN_MSG0                                                              0x9804ECAC
#define PCIE_VEN_MSG0_reg_addr                                                     "0xD804ECAC"
#define PCIE_VEN_MSG0_reg                                                          0xD804ECAC
#define PCIE_VEN_MSG1                                                              0x9804ECB0
#define PCIE_VEN_MSG1_reg_addr                                                     "0xD804ECB0"
#define PCIE_VEN_MSG1_reg                                                          0xD804ECB0
#define PCIE_MAC_ST                                                                0x9804ECB4
#define PCIE_MAC_ST_reg_addr                                                       "0xD804ECB4"
#define PCIE_MAC_ST_reg                                                            0xD804ECB4
#define PCIE_UNLOCK_MSG                                                            0x9804ECB8
#define PCIE_UNLOCK_MSG_reg_addr                                                   "0xD804ECB8"
#define PCIE_UNLOCK_MSG_reg                                                        0xD804ECB8
#define PCIE_SCTCH                                                                 0x9804ECBC
#define PCIE_SCTCH_reg_addr                                                        "0xD804ECBC"
#define PCIE_SCTCH_reg                                                             0xD804ECBC
#define PCIE_LOOP_DATA_2_reg_addr                                                  "0xD804ECC8"
#define PCIE_LOOP_DATA_3_reg_addr                                                  "0xD804ECCC"
#define PCIE_LOOP_DATA_0_reg                                                       0xD804ECC0
#define PCIE_MSI_TRAN                                                              0x9804ECD0
#define PCIE_MSI_TRAN_reg_addr                                                     "0xD804ECD0"
#define PCIE_MSI_TRAN_reg                                                          0xD804ECD0
#define PCIE_MSI_DATA                                                              0x9804ECD4
#define PCIE_MSI_DATA_reg_addr                                                     "0xD804ECD4"
#define PCIE_MSI_DATA_reg                                                          0xD804ECD4
#define PCIE_LINK_ST                                                               0x9804ECE8
#define PCIE_LINK_ST_reg_addr                                                      "0xD804ECE8"
#define PCIE_LINK_ST_reg                                                           0xD804ECE8
#define PCIE_BIST_CTRL                                                             0x9804ECEC
#define PCIE_BIST_CTRL_reg_addr                                                    "0xD804ECEC"
#define PCIE_BIST_CTRL_reg                                                         0xD804ECEC
#define PCIE_BIST_STATUS                                                           0x9804ECF0
#define PCIE_BIST_STATUS_reg_addr                                                  "0xD804ECF0"
#define PCIE_BIST_STATUS_reg                                                       0xD804ECF0
#define PCIE_SRAM_PWRDN                                                            0x9804ECF4
#define PCIE_SRAM_PWRDN_reg_addr                                                   "0xD804ECF4"
#define PCIE_SRAM_PWRDN_reg                                                        0xD804ECF4
#define PCIE_VEN_MSG2                                                              0x9804ECF8
#define PCIE_VEN_MSG2_reg_addr                                                     "0xD804ECF8"
#define PCIE_VEN_MSG2_reg                                                          0xD804ECF8
#define PCIE_PCI_BASE                                                              0x9804ECFC
#define PCIE_PCI_BASE_reg_addr                                                     "0xD804ECFC"
#define PCIE_PCI_BASE_reg                                                          0xD804ECFC
#define PCIE_PCI_MASK                                                              0x9804ED00
#define PCIE_PCI_MASK_reg_addr                                                     "0xD804ED00"
#define PCIE_PCI_MASK_reg                                                          0xD804ED00
#define PCIE_PCI_TRANS                                                             0x9804ED04
#define PCIE_PCI_TRANS_reg_addr                                                    "0xD804ED04"
#define PCIE_PCI_TRANS_reg                                                         0xD804ED04
#define PCIE_PCI_LTR                                                               0x9804ED08
#define PCIE_PCI_LTR_reg_addr                                                      "0xD804ED08"
#define PCIE_PCI_LTR_reg                                                           0xD804ED08
#define PCIE_TMP_REG_3                                                             0x9804ECE4
#define PCIE_TMP_REG_0_reg_addr                                                    "0xD804ECD8"
#define PCIE_TMP_REG_1_reg_addr                                                    "0xD804ECDC"
#define PCIE_TMP_REG_2_reg_addr                                                    "0xD804ECE0"
#define PCIE_TMP_REG_3_reg_addr                                                    "0xD804ECE4"
#define PCIE_TMP_REG_0_reg                                                         0xD804ECD8
#define PCIE_TMP_REG_1_reg                                                         0xD804ECDC
#define PCIE_TMP_REG_2_reg                                                         0xD804ECE0
#define PCIE_TMP_REG_3_reg                                                         0xD804ECE4
#define PCIE_MAC_ID                                                                0x119711ec
#define PCIE_CLKREQ_MUX_PAD                                                        0x00000004
#define PCIE_0x7C_LINK_CAPABILITY                                                  0x00737c11
#define PCIE_0x80_LINK_CAPABILITY                                                  0x30110008
#define PCIE_0x9C_LINK_CAPABILITY2                                                 0x00000002
#define PCIE_0xa0_LINK_CONTROL2_LINK_STATUS2                                       0x00000000
#define PCIE_PCI_EP_BASE_PA                                                        0x9804f000
#define PCIE_PCI_EP_BASE_VA                                                        0xD804f000
#endif
